apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mquaqkr5y-nodejs 
  janus-idp.io/tekton: mquaqkr5y-nodejs
  backstage.io/kubernetes-id: mquaqkr5y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mquaqkr5y-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml